sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  
install: mvn install --quiet -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn --fail-at-end install -Ptomee-embedded-arquillian -B
